### ISSUE TITLE
README has text from customizer package. 

### ISSUE THREAD

**Issue by skyshab** [themehybrid/hybrid-theme#1]
In the readme file, just above the copyright section is a line of text that appears to be a remnant from the hybrid customizer package readme. 

"This is basically going to set up and ready any JS-based customizer controls."

This should be removed.

**Comment by saas786** [comment]
closed in: https://github.com/themehybrid/hybrid-theme/commit/bfd40be34cf8c70cb0a8d8f8ed6b87996904f7a6
