### ISSUE TITLE
Hook names need to be updated

### ISSUE THREAD

**Issue by justintadlock** [themehybrid/hybrid-theme#2]
Hook names should follow the paths so they're easy to remember.  For example, `hybrid/site/title` becomes `hybrid/theme/site/title`.

**Comment by justintadlock** [comment]
Reopening for: https://github.com/themehybrid/hybrid-theme/pull/3#issuecomment-796932429

**Comment by saas786** [comment]
> Reopening for: [#3 (comment)](https://github.com/themehybrid/hybrid-theme/pull/3#issuecomment-796932429)

Should be better now.

**Comment by saas786** [comment]
Closing. Reopen if still needed.
